name: GitHub Pages

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.0.0
        with:
          target_branch: gh-pages
          build_dir: /
